version: 2
updates:
  # - package-ecosystem: "mix"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"

  # - package-ecosystem: "npm"
  #   directory: "/assets"
  #   schedule:
  #     interval: "monthly"

  # - package-ecosystem: "npm"
  #   directory: "/website"
  #   schedule:
  #     interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/grafana"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
