name: Spell check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  spell_check:
    name: Spell check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Spell check
        uses: crate-ci/typos@5c19779cb52ea50e151f5a10333ccd269227b5ae # v1.41.0
