name: Spell check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  spell_check:
    name: Spell check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Spell check
        uses: crate-ci/typos@2d0ce569feab1f8752f1dde43cc2f2aa53236e06 # v1.40.0
