name: Spell check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  spell_check:
    name: Spell check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Spell check
        uses: crate-ci/typos@5c19779cb52ea50e151f5a10333ccd269227b5ae # v1.41.0
